// <auto-generated />
using System;
using FitnessPP;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessPP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620065054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Client_Service", b =>
                {
                    b.Property<Guid>("client_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("service_id")
                        .HasColumnType("TEXT");

                    b.HasKey("client_id", "service_id");

                    b.HasIndex("service_id");

                    b.ToTable("Client_Service");
                });

            modelBuilder.Entity("FitnessPP.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LockerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FitnessPP.Models.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Lockers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3637610d-ef7d-495d-956a-6b2680323bb1"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("7973fdec-0a81-4f1d-b89d-1832caee562e"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("4c55cf23-025c-4085-b6cb-ee97026c03dc"),
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("08af3429-7154-4a83-bcf8-833f1e7cdf4e"),
                            Number = 4
                        },
                        new
                        {
                            Id = new Guid("89c4f198-0165-4f1f-8f87-0469626890ac"),
                            Number = 5
                        },
                        new
                        {
                            Id = new Guid("faf1b537-4cfb-4e00-969a-2bde5043f323"),
                            Number = 6
                        },
                        new
                        {
                            Id = new Guid("109b6aed-7fb6-42d0-b0e5-c388a92da229"),
                            Number = 7
                        },
                        new
                        {
                            Id = new Guid("5b7ce47a-54b9-4b52-8a0f-a4c2ddbdf871"),
                            Number = 8
                        },
                        new
                        {
                            Id = new Guid("873c0306-3e0c-40ab-82d8-49ead0735636"),
                            Number = 9
                        },
                        new
                        {
                            Id = new Guid("e3bb7fe0-0155-4f8a-826e-367bdd820b7b"),
                            Number = 10
                        },
                        new
                        {
                            Id = new Guid("a816fe93-57a3-411a-9c71-8c10e87427a8"),
                            Number = 11
                        },
                        new
                        {
                            Id = new Guid("01c0f3ed-f25b-49f2-8dab-165dba955a9a"),
                            Number = 12
                        },
                        new
                        {
                            Id = new Guid("882f32f7-9f4d-45ce-ba97-aa4dae118c50"),
                            Number = 13
                        },
                        new
                        {
                            Id = new Guid("350ae3c0-b734-49be-a9df-fcc1e205f802"),
                            Number = 14
                        },
                        new
                        {
                            Id = new Guid("0c7af1e7-bd39-46e9-89c7-1e8d3e6df1b8"),
                            Number = 15
                        },
                        new
                        {
                            Id = new Guid("0e41e21b-4a8f-49a5-b398-f0bb0f58253d"),
                            Number = 16
                        },
                        new
                        {
                            Id = new Guid("79b6996b-a629-46a7-b7eb-ca88909aa3ce"),
                            Number = 17
                        },
                        new
                        {
                            Id = new Guid("7ef36b9b-696a-4e4a-b050-ca5b10a8e54b"),
                            Number = 18
                        },
                        new
                        {
                            Id = new Guid("a8242e7b-b834-44f2-954a-481ac27edb3a"),
                            Number = 19
                        },
                        new
                        {
                            Id = new Guid("94e3b795-e521-4527-86af-8af7a038dfef"),
                            Number = 20
                        });
                });

            modelBuilder.Entity("FitnessPP.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = "SOLARIUM",
                            Name = "Солярий",
                            Price = 400
                        },
                        new
                        {
                            Id = "POOL",
                            Name = "Бассейн",
                            Price = 200
                        },
                        new
                        {
                            Id = "SAUNA",
                            Name = "Сауна",
                            Price = 0
                        },
                        new
                        {
                            Id = "CRYOSAUNA",
                            Name = "Криосауна",
                            Price = 1000
                        },
                        new
                        {
                            Id = "CROSSFIT",
                            Name = "Кроссфит",
                            Price = 500
                        });
                });

            modelBuilder.Entity("FitnessPP.Models.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("Client_Service", b =>
                {
                    b.HasOne("FitnessPP.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPP.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessPP.Models.Client", b =>
                {
                    b.HasOne("FitnessPP.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FitnessPP.Models.Locker", b =>
                {
                    b.HasOne("FitnessPP.Models.Client", "Client")
                        .WithOne("Locker")
                        .HasForeignKey("FitnessPP.Models.Locker", "ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessPP.Models.Client", b =>
                {
                    b.Navigation("Locker");
                });
#pragma warning restore 612, 618
        }
    }
}
